version: '3.5'

services:
  web:
    container_name: python-retry-middleware-app-web
    env_file:
      - .env
    environment:
      REDIS_URL: 'redis://redis:6379/0'
    build:
      dockerfile: ./sample-apps/retry-middleware-app/docker/web/Dockerfile
      context: ../../
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src

  redis:
    image: redis:latest
