version: '3.5'

services:
  web:
    container_name: python-search-results-paging-app-web
    env_file:
      - .env
    environment:
      REDIS_URL: 'redis://redis:6379/0'
    build:
      dockerfile: ./sample-apps/search-results-paging-app/docker/web/Dockerfile
      context: ../../
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src

  redis:
    image: redis:6.0
