version: '3.5'

services:
  web:
    container_name: python-webhooks-app-web
    env_file:
      - .env
    build:
      dockerfile: ./sample-apps/webhooks-app/docker/web/Dockerfile
      context: ../../
    volumes:
      - ./src:/app/src
  ngrok:
    image: gtriggiano/ngrok-tunnel
    ports:
      - 4040:4040
    environment:
      TARGET_HOST: web
      TARGET_PORT: 5000
    depends_on:
      - web
